### ISSUE TITLE
Moving the repo to pacman-project account

### ISSUE THREAD

**Issue by carlosjoserg** [pacman-project/gaussian-object-modelling#8]
Hi there,

I think it is wise to transfer this repository to the pacman-project account/workspace.

According to github, everything redirects automatically, however, they recommend to update the remotes (either using git remote commands or simply re-clone from the new address).

So, I'm gonna do this on Monday afternoon around 15:00h. I'll let you know before to check if you have all in the cloud and properly backed up.

Best

**Comment by Tabjones** [comment]
:+1:

**Comment by memnone** [comment]
Good!

Today I'm gonna be in the lab testing the grasping with info gain
algorithm.  Anyway let me know if the atlas code works fine. I have changed
carlos' code in order to compute the fricative only for the new points
without re-computing the entire kernel. No idea if it works fine cause I
still don't have a proper visualisation.

Best,
Claudio

**Comment by carlosjoserg** [comment]
So, let me know when you are ready so I can transfer it to the pacman-project account.

**Comment by Tabjones** [comment]
I'm not working on the repo today. you can transfer it whenever you want

**Comment by carlosjoserg** [comment]
Ok.  @memnone  ?

**Comment by memnone** [comment]
It's OK with me too.
Cheers

**Comment by carlosjoserg** [comment]
thanks

**Comment by carlosjoserg** [comment]
Done, let me know if you find troubles.
